#ifndef TARGETS_ARM_INC_HARDWARECONFIG_H_
#define TARGETS_ARM_INC_HARDWARECONFIG_H_

constexpr static int ENCODER_DEBOUNCE_STABLE = 5;
constexpr static int BUTTON_DEBOUNCE_STABLE = 20;
constexpr static int ENCODER_PRESC = 4;


#endif  // TARGETS_ARM_INC_HARDWARECONFIG_H_
